[build]
  publish = "static"  # If you have a directory for static content
  functions = "functions"  # Folder where Python functions reside
  command = "python3 app.py"  # Update this with your actual build command if it's different
  publish = "build"  # The directory to publish after build. Adjust as necessary.

[build.environment]
  PYTHON_VERSION = "3.12.0"  # Make sure to use Python 3.12.0
  NODE_VERSION = "14"  # Specify the Node.js version (14.x is a common choice for many apps)


[[plugins]]
  package = "@netlify/plugin-functions-install-core"
